### ISSUE TITLE
Got init.scope issue, please help.

### ISSUE THREAD

**Issue by krime** [univention/ucs-appliance-container#2]
Hi, I try to run with univention/ucs-master-amd64, and then I got the following error message, can anyone tell me what's wrong with the running?

```text
Set hostname to <master>.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

the running command is follow the description of univention/ucs-master-amd64:
```sh
docker run -d -it --name master_container \
    --hostname=master \
    -e domainname=testdomain.intranet \
    -e rootpwd=<Chosen password> \
    -p 8011:80 \
    -e container=docker \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --tmpfs /run --tmpfs /run/lock \
    --cap-add=SYS_ADMIN \
    --restart unless-stopped \
    univention/ucs-master-amd64 /sbin/init
```

**Comment by reqa** [comment]
Please note that the univention/ucs-master-amd64 container image is not built from this repository. Instead it's based on an earlier approach of doing things (e.g. it is already differenciated with respect to the server role). So the place to discuss this would be https://help.univention.com/ . One thing that I would suggest to check is the message `Read-only file system`: We tested this with docker configured for the overlay2 storage driver, which we ran on an ext4 filesystem. So that should work.

**Comment by krime** [comment]
Thanks for the suggestion.
